spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.212:3306/mybatis
    driver-class-name: com.mysql.jdbc.Driver
#指定redis地址
  redis:
    host: 192.168.10.212
# 开启驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
